const allTiles = [
    { isMarked: false, isShown: true, name: 'Adi Nisimov' },
    { isMarked: false, isShown: true, name: 'Amit Shrim' },
    { isMarked: false, isShown: true, name: 'Anat Asman (Hani)' },
    { isMarked: false, isShown: true, name: 'Arnon Parenti' },
    { isMarked: false, isShown: true, name: 'Aviv Danziger' },
    { isMarked: false, isShown: true, name: 'Benjamin Shinar' },
    { isMarked: false, isShown: true, name: 'Beny Bary' },
    { isMarked: false, isShown: true, name: 'Boris Ulyanskiy' },
    { isMarked: false, isShown: true, name: 'Chen Polat' },
    { isMarked: false, isShown: true, name: 'Coral Grichener' },
    { isMarked: false, isShown: true, name: 'Daniel Kit' },
    { isMarked: false, isShown: true, name: 'Daniel Meir' },
    { isMarked: false, isShown: true, name: 'Danielle Shneor' },
    { isMarked: false, isShown: true, name: 'Danielle Shtub' },
    { isMarked: false, isShown: true, name: 'Dvir Harnoy' },
    { isMarked: false, isShown: true, name: 'Eden Aran' },
    { isMarked: false, isShown: true, name: 'Einav Axler' },
    { isMarked: false, isShown: true, name: 'Elinor Benchimol' },
    { isMarked: false, isShown: true, name: 'Eyal Orel' },
    { isMarked: false, isShown: true, name: 'Gai Regev' },
    { isMarked: false, isShown: true, name: 'Gil Levi' },
    { isMarked: false, isShown: true, name: 'Gil Shouchami' },
    { isMarked: false, isShown: true, name: 'Gilad C Keren' },
    { isMarked: false, isShown: true, name: 'Guy Zoltsman' },
    { isMarked: false, isShown: true, name: 'Hadar Tishler' },
    { isMarked: false, isShown: true, name: 'Ilan Danielov' },
    { isMarked: false, isShown: true, name: 'Inbar Ruben' },
    { isMarked: false, isShown: true, name: 'Ivy V Purple' },
    { isMarked: false, isShown: true, name: 'John Shepard (Pigi)' },
    { isMarked: false, isShown: true, name: 'Julia Kiviliov' },
    { isMarked: false, isShown: true, name: 'Keren Shoval' },
    { isMarked: false, isShown: true, name: 'Kimberly Marie' },
    { isMarked: false, isShown: true, name: 'Libby Wein' },
    { isMarked: false, isShown: true, name: 'Linn Tamar Omer' },
    { isMarked: false, isShown: true, name: 'Lior Abutbul' },
    { isMarked: false, isShown: true, name: 'Lior Uzan' },
    { isMarked: false, isShown: true, name: 'Liran Avda' },
    { isMarked: false, isShown: true, name: 'Maayan Kuple' },
    { isMarked: false, isShown: true, name: 'Maria Sherbakov' },
    { isMarked: false, isShown: true, name: 'Nadav Shachar' },
    { isMarked: false, isShown: true, name: 'Noamm Ungerr' },
    { isMarked: false, isShown: true, name: 'Oded Spitzer' },
    { isMarked: false, isShown: true, name: 'Olly Kagan' },
    { isMarked: false, isShown: true, name: 'Omer Zauber' },
    { isMarked: false, isShown: true, name: 'Omry Shapira' },
    { isMarked: false, isShown: true, name: 'Or Chen' },
    { isMarked: false, isShown: true, name: 'Or Zellner' },
    { isMarked: false, isShown: true, name: 'Ora Druker' },
    { isMarked: false, isShown: true, name: 'Peleg Maimon' },
    { isMarked: false, isShown: true, name: 'Raz Lubinsky' },
    { isMarked: false, isShown: true, name: 'Revital Gold' },
    { isMarked: false, isShown: true, name: 'Ron Harnik' },
    { isMarked: false, isShown: true, name: 'Sasha Agamyan' },
    { isMarked: false, isShown: true, name: 'Shany Ox' },
    { isMarked: false, isShown: true, name: 'Shay Zeldis' },
    { isMarked: false, isShown: true, name: 'Tamar Cohen' },
    { isMarked: false, isShown: true, name: 'Tatyana Chekulaev' },
    { isMarked: false, isShown: true, name: 'Yael Vachbroit Malosh' },
    { isMarked: false, isShown: true, name: 'Yagel Gamliel' },
    { isMarked: false, isShown: true, name: 'Yana Fesh' },
    { isMarked: false, isShown: true, name: 'Yevgeni Furman' },
    { isMarked: false, isShown: true, name: 'Yogev Levy' },
    { isMarked: false, isShown: true, name: 'Yomiran Nissan' },
    { isMarked: false, isShown: true, name: 'Yuval Sol Boker' },
    { isMarked: false, isShown: true, name: 'Zingi Ramirez' }
]

module.exports={
    allTiles
}